### ISSUE TITLE
Is there Logging for Changes done when fixing the document?

### ISSUE THREAD

**Issue by Somu76** [desjarlais/Office-File-Explorer-v2#5]
**Is your feature request related to a problem? Please describe.**
I was able to run the tool to fix a document, but the output I see only had two statements as below. How can I get more details on what these mean?
====================
Corrupt Textboxes Fixed
Corrupt Delete Revisions Fixed
==================

**Describe the solution you'd like**
Would love to see a log file that documents the actions being taken or issues being checked for.

**Comment by desjarlais** [comment]
That is a good idea, I will start adding more details about the fixes.  I have them documented in the code, but logging that out for each attempted fix is a good idea.

**Comment by desjarlais** [comment]
@Somu76 is something like this good or should I include more detail?

List Styles Fixed - More information here https://github.com/desjarlais/Office-File-Explorer-v2/wiki/Fix-Document-Feature#fix-list-styles"

I'm essentially just putting each type of fix and what it does at a high level in the wiki and pointing to it.  Or were you looking for more of a tag by tag level of detail?

**Comment by desjarlais** [comment]
Keeping track of each tag that was removed in the file is not something I have time to add in, so for now I'll keep updating the general logic in the wiki and output that for each fix that gets applied when Fix Document is used.  Please reopen if you have other feedback to provide or another idea for how to document what is happening when the feature is used.
